[theme]
primaryColor             = "#5B5CD6"
backgroundColor          = "#F5F7F9"
secondaryBackgroundColor = "#EEEEF9"
textColor                = "#212121"
font                     = "sans serif"

[server]
headless            = true
